"""empty message

Revision ID: 091e9f423ca7
Revises: e9dcc47e170f
Create Date: 2021-06-05 20:37:38.580820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091e9f423ca7'
down_revision = 'e9dcc47e170f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gun', sa.Column('description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gun', 'description')
    # ### end Alembic commands ###
