"""empty message

Revision ID: 27060c444cdd
Revises: b3923ab0ae03
Create Date: 2021-06-01 16:42:35.745183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27060c444cdd'
down_revision = 'b3923ab0ae03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fname', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('lname', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    # ### end Alembic commands ###
