"""empty message

Revision ID: a255ae0f765b
Revises: e14cd52d1d53
Create Date: 2021-06-07 21:04:37.967882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a255ae0f765b'
down_revision = 'e14cd52d1d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gun', sa.Column('displayCategoryName', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gun', 'displayCategoryName')
    # ### end Alembic commands ###
