"""empty message

Revision ID: e14cd52d1d53
Revises: b6190523bb4f
Create Date: 2021-06-07 17:39:48.399916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14cd52d1d53'
down_revision = 'b6190523bb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('imageURL', sa.String(length=120), nullable=True))
    op.add_column('gun', sa.Column('displayName', sa.String(length=120), nullable=False))
    op.add_column('gun', sa.Column('imageURL', sa.String(length=120), nullable=True))
    op.alter_column('gun', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('gun', 'category',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_unique_constraint(None, 'gun', ['name'])
    op.create_unique_constraint(None, 'gun', ['displayName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gun', type_='unique')
    op.drop_constraint(None, 'gun', type_='unique')
    op.alter_column('gun', 'category',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('gun', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('gun', 'imageURL')
    op.drop_column('gun', 'displayName')
    op.drop_column('activity', 'imageURL')
    # ### end Alembic commands ###
