"""empty message

<<<<<<< HEAD:migrations/versions/59d512ad01b2_.py
Revision ID: 59d512ad01b2
Revises: 
Create Date: 2021-06-07 23:42:51.144772
=======
Revision ID: e4b72d6f78cf
Revises: 
Create Date: 2021-06-08 16:38:29.149431
>>>>>>> 22834448eae4abe23bf244728360cb01a340d350:migrations/versions/e4b72d6f78cf_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/59d512ad01b2_.py
revision = '59d512ad01b2'
=======
revision = 'e4b72d6f78cf'
>>>>>>> 22834448eae4abe23bf244728360cb01a340d350:migrations/versions/e4b72d6f78cf_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('displayName', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('imageURL', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('displayName', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('caliber', sa.String(length=120), nullable=True),
    sa.Column('barrelLength', sa.String(length=120), nullable=True),
    sa.Column('capacity', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('displayCategoryName', sa.String(length=120), nullable=False),
    sa.Column('guntype', sa.String(length=120), nullable=True),
    sa.Column('weight', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('imageURL', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('displayName'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=80), nullable=False),
    sa.Column('lname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gun_activities',
    sa.Column('gun_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['gun_id'], ['gun.id'], ),
    sa.PrimaryKeyConstraint('gun_id', 'activity_id')
    )
    op.create_table('gun_bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gun_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gun_id'], ['gun.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'gun_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gun_bookmarks')
    op.drop_table('gun_activities')
    op.drop_table('user')
    op.drop_table('gun')
    op.drop_table('activity')
    # ### end Alembic commands ###
